/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MatrixTrainingsRouteImport } from './routes/matrix-trainings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DetailCollabIdRouteImport } from './routes/detail-collab.$id'

const MatrixTrainingsRoute = MatrixTrainingsRouteImport.update({
  id: '/matrix-trainings',
  path: '/matrix-trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailCollabIdRoute = DetailCollabIdRouteImport.update({
  id: '/detail-collab/$id',
  path: '/detail-collab/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matrix-trainings': typeof MatrixTrainingsRoute
  '/detail-collab/$id': typeof DetailCollabIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matrix-trainings': typeof MatrixTrainingsRoute
  '/detail-collab/$id': typeof DetailCollabIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matrix-trainings': typeof MatrixTrainingsRoute
  '/detail-collab/$id': typeof DetailCollabIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/matrix-trainings' | '/detail-collab/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/matrix-trainings' | '/detail-collab/$id'
  id: '__root__' | '/' | '/matrix-trainings' | '/detail-collab/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatrixTrainingsRoute: typeof MatrixTrainingsRoute
  DetailCollabIdRoute: typeof DetailCollabIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/matrix-trainings': {
      id: '/matrix-trainings'
      path: '/matrix-trainings'
      fullPath: '/matrix-trainings'
      preLoaderRoute: typeof MatrixTrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail-collab/$id': {
      id: '/detail-collab/$id'
      path: '/detail-collab/$id'
      fullPath: '/detail-collab/$id'
      preLoaderRoute: typeof DetailCollabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatrixTrainingsRoute: MatrixTrainingsRoute,
  DetailCollabIdRoute: DetailCollabIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
